extDomains:
  ftn:
redis:
  host: localhost
  port: 6379
  password: CBkaPkcF4hs4
  db: 0
  expirationTime: 3600
db:
  lukexDb:
    adapter: mysql
    database: lukex
    username: lukex
    password: Lukex2010.
    host: 107.170.208.14
    port: 3306
    idleConns: 10
    openConns: 100
jwt:
  alg: HS512
  key: TDE0djNAMjAxOFAzUlVDMEwwTUJJNEA=
  exp: 86400
app:
  port: 8080
logEnabled: true
